project:
  type: book
  output-dir: docs
  preview:
    browser: true

# bootstraping  https://acclab.github.io/dabestr/articles/tutorial_basics.html
# causal inference https://ngreifer.github.io/software/ causal
# fix honest_plots chatbot
# fix clear_plots chatbot

book:
  title: "Applied Biostatistics"
  author: "Yaniv Brandvain"
  date: today
  sidebar:
    search: true
    background: '#3A5F0B' #"#9f86c0"
    logo: "figs/fun_figs/stamp.png"
  chapters:
    - index.qmd
    - book_sections/clarkia_and_its_data/clarkia_and_its_data.qmd
    - book_sections/example_mini/varType.qmd
    - book_sections/filler.qmd
    - book_sections/intro2r_index.qmd
    - part: book_sections/getting_started.qmd
      chapters: 
        - book_sections/getting_started/functions_and_vectors.qmd
        - book_sections/getting_started/loading_packages_and_data.qmd
        - book_sections/getting_started/data_types.qmd
        - book_sections/getting_started/rstudio_orientation.qmd
        - book_sections/getting_started/getting_started_summary.qmd
    - part: book_sections/data_in_R.qmd
      chapters: 
        - book_sections/data_in_R/add_vars.qmd
        - book_sections/data_in_R/select_vars.qmd
        - book_sections/data_in_R/summarize_vars.qmd
        - book_sections/data_in_R/choose_rows.qmd
        - book_sections/data_in_R/data_in_R_summary.qmd
    - part: book_sections/intro_to_ggplot.qmd
      chapters: 
        - book_sections/intro_to_ggplot/one_continuous.qmd
        - book_sections/intro_to_ggplot/saving_ggplots.qmd
        - book_sections/intro_to_ggplot/cont_cat.qmd
        - book_sections/intro_to_ggplot/two_categorical.qmd
        - book_sections/intro_to_ggplot/two_continuous.qmd
        - book_sections/intro_to_ggplot/many_explanatory.qmd
        - book_sections/intro_to_ggplot/ggplot_summary.qmd
    - part: book_sections/reproducible_science.qmd
      chapters: 
        - book_sections/reproducible_science/collecting_data.qmd
        - book_sections/reproducible_science/reproducible_analyses.qmd
        - book_sections/reproducible_science/reproducible_summary.qmd  
    - book_sections/filler.qmd
    - book_sections/summarizing_data_index.qmd
    - part: book_sections/univariate_summaries.qmd
      chapters: 
        - book_sections/univariate_summaries/summarizing_shape.qmd
        - book_sections/univariate_summaries/changing_shape.qmd
        - book_sections/univariate_summaries/summarizing_center.qmd
        - book_sections/univariate_summaries/summarizing_variability.qmd
        - book_sections/univariate_summaries/summarizing_summaries.qmd
    - part: book_sections/associations.qmd
      chapters: 
        - book_sections/associations/cat_cont.qmd
        - book_sections/associations/two_categorical_vars.qmd
        - book_sections/associations/cont_cont.qmd
        - book_sections/associations/summarizing_associations.qmd
    - part: book_sections/linear_models.qmd 
      chapters: 
        - book_sections/linear_models/mean.qmd 
        - book_sections/linear_models/lm_cat_pred.qmd
        - book_sections/linear_models/regression.qmd
        - book_sections/linear_models/two_predictors.qmd
        - book_sections/linear_models/lm_summary.qmd
    - part: book_sections/ordination.qmd
      chapters:         
        - book_sections/ordination/pca.qmd
        - book_sections/ordination/pcaII.qmd
        - book_sections/ordination/pcaIII.qmd
        - book_sections/ordination/pcalternatives.qmd
        - book_sections/ordination/ordination_summary.qmd
    - part: book_sections/data_viz.qmd
      chapters:         
        - book_sections/data_viz/audience&delivery.qmd
        - book_sections/data_viz/honest_plots.qmd
        - book_sections/data_viz/transparent_plots.qmd
        - book_sections/data_viz/clear_plots.qmd
        - book_sections/data_viz/avoid_distractions.qmd
        - book_sections/data_viz/accessible_plots.qmd
        - book_sections/data_viz/writing_about_figures.qmd
        - book_sections/data_viz/dataviz_summary.qmd
    - part: book_sections/betteR_plots.qmd
      chapters:         
        - book_sections/betteR_plots/plotting_tools.qmd
        - book_sections/betteR_plots/cleaR_plots.qmd
        - book_sections/betteR_plots/plots_foR_medium.qmd
        - book_sections/betteR_plots/betteR_plots_summary.qmd    
    - toc.qmd
    - references.qmd


 


bibliography: ["assets/modeling.bib", "assets/packages.bib"]
csl: 'assets/apa-single-spaced.csl'

format:
  html:
    theme: 
      - flatly
      - "assets/theme_corrected.scss"
    css: ["assets/sticky-notes.css", "assets/table-styles.css", "assets/webex.css"]
    include-after-body: assets/webex.js
    code-copy: true
    highlight-style: zenburn
    mainfont: 'Crimson Text'
    fontsize: '14pt'
    linestretch: '1.5em'
    linkcolor: '#20a2a3' 
    toc: false
    link-external-newwindow: true
editor: source
filters:
 - webr
 - shinylive