project:
  type: book
  output-dir: docs
  preview:
    browser: true


book:
  title: "Applied Biostatistics"
  author: "Yaniv Brandvain"
  date: today
  sidebar:
    search: true
    background: '#3A5F0B' #"#9f86c0"
    logo: "figs/fun_figs/stamp.png"
  chapters:
    - index.qmd
    - book_sections/clarkia_and_its_data/clarkia_and_its_data.qmd
    - book_sections/example_mini/varType.qmd
    - book_sections/intro2r_index.qmd
    - part: book_sections/getting_started.qmd
      chapters: 
        - book_sections/getting_started/functions_and_vectors.qmd
        - book_sections/getting_started/loading_packages_and_data.qmd
        - book_sections/getting_started/data_types.qmd
        - book_sections/getting_started/rstudio_orientation.qmd
        - book_sections/getting_started/getting_started_summary.qmd
    - part: book_sections/data_in_R.qmd
      chapters: 
        - book_sections/data_in_R/add_vars.qmd
        - book_sections/data_in_R/select_vars.qmd
        - book_sections/data_in_R/summarize_vars.qmd
        - book_sections/data_in_R/choose_rows.qmd
        - book_sections/data_in_R/data_in_R_summary.qmd
    - part: book_sections/intro_to_ggplot.qmd
      chapters: 
        - book_sections/intro_to_ggplot/one_continuous.qmd
        - book_sections/intro_to_ggplot/saving_ggplots.qmd
        - book_sections/intro_to_ggplot/cont_cat.qmd
        - book_sections/intro_to_ggplot/two_categorical.qmd
        - book_sections/intro_to_ggplot/two_continuous.qmd
        - book_sections/intro_to_ggplot/many_explanatory.qmd
        - book_sections/intro_to_ggplot/ggplot_summary.qmd
    - part: book_sections/reproducible_science.qmd
      chapters: 
        - book_sections/reproducible_science/collecting_data.qmd
        - book_sections/reproducible_science/reproducible_analyses.qmd
        - book_sections/reproducible_science/reproducible_summary.qmd  
    - toc.qmd
    - references.qmd


 


bibliography: ["assets/modeling.bib", "assets/packages.bib"]
csl: 'assets/apa-single-spaced.csl'

format:
  html:
    theme: 
      - flatly
      - "assets/theme_corrected.scss"
    css: ["assets/sticky-notes.css", "assets/table-styles.css", "assets/webex.css"]
    include-after-body: assets/webex.js
    code-copy: true
    highlight-style: zenburn
    mainfont: 'Crimson Text'
    fontsize: '14pt'
    linestretch: '1.5em'
    linkcolor: '#20a2a3' 
    toc: false
    link-external-newwindow: true
editor: source
filters:
 - webr